name: Codecov Code Coverage

on:
  - push
  - workflow_dispatch


jobs:
  test:
    name: Code Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x
      - name: Tests
        run: deno test -r --coverage=./coverage/cov --doc --junit-path=./coverage/junit/test.xml --permit-no-files --unstable
      - name: Code Coverage
        run: deno coverage --lcov coverage/cov/ > coverage/cov.lcov
      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}